fix: enable GH releases in CD (#2361)
* fix: enable GH releases in CD

* chore: add comment explaining expanded permissions for GHA

diff --git a/scripts/publish-release b/scripts/publish-release
--- a/scripts/publish-release
+++ b/scripts/publish-release
@@ -10,20 +10,20 @@ if [[ "${CURRENT_BRANCH}" != *"${RELEASE_PREFIX}"*  ]]; then
   exit 1
 fi
 
-#if !(command -v gh > /dev/null); then
-#  echo "GitHub CLI is required for this release script."
-#  echo "Please install GitHub CLI and try again:"
-#  echo "https://github.com/cli/cli#installation"
-#  exit 1
-#fi
+if !(command -v gh > /dev/null); then
+  echo "GitHub CLI is required for this release script."
+  echo "Please install GitHub CLI and try again:"
+  echo "https://github.com/cli/cli#installation"
+  exit 1
+fi
 
-## hostname is necessary just in case you are logged into the CLI
-## GitHub enterprise instance
-#if !(gh auth status --hostname "github.com" > /dev/null 2>&1); then
-#  echo "Not logged into github".
-#  echo "Please run: gh auth login"
-#  exit 1
-#fi
+# hostname is necessary just in case you are logged into the CLI
+# GitHub enterprise instance
+if !(gh auth status --hostname "github.com" > /dev/null 2>&1); then
+  echo "Not logged into github".
+  echo "Please run: gh auth login"
+  exit 1
+fi
 
 git pull --rebase origin "${CURRENT_BRANCH}"
 # The --force overrides local tags.
@@ -51,11 +51,10 @@ echo "publishing packages to npm..."
 yarn lerna publish --yes from-package
 
 
-#LAST_PUBLISHED_TAG=$(git tag --sort="-version:refname" --list --format="%(refname:strip=2)" | head -n1)
+LAST_PUBLISHED_TAG=$(git tag --sort="-version:refname" --list --format="%(refname:strip=2)" | head -n1)
 
 git tag "${TAG_NAME}" -m "${TAG_NAME}"
 git push origin "${TAG_NAME}"
 
-# temporary disable while waiting on service account approval
-#RELEASE_NOTES=$(git log --graph --format="%h %s" "${LAST_PUBLISHED_TAG}...${TAG_NAME}~1")
-#gh release create "${TAG_NAME}" --title="${TAG_NAME}" --notes="${RELEASE_NOTES}"
+RELEASE_NOTES=$(git log --graph --format="%h %s" "${LAST_PUBLISHED_TAG}...${TAG_NAME}~1")
+gh release create "${TAG_NAME}" --title="${TAG_NAME}" --notes="${RELEASE_NOTES}"
